# Generated by Django 3.2.14 on 2024-05-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMP_CRM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empmodel',
            name='emp_place',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
